// Code generated by mockery v2.53.6. DO NOT EDIT.

package schedule

import (
	context "context"

	model "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// mockScheduleRepo is an autogenerated mock type for the scheduleRepo type
type mockScheduleRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, schedule
func (_m *mockScheduleRepo) Create(ctx context.Context, schedule *model.Schedule) (*model.Schedule, error) {
	ret := _m.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Schedule) (*model.Schedule, error)); ok {
		return rf(ctx, schedule)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Schedule) *model.Schedule); ok {
		r0 = rf(ctx, schedule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Schedule) error); ok {
		r1 = rf(ctx, schedule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockScheduleRepo creates a new instance of mockScheduleRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockScheduleRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockScheduleRepo {
	mock := &mockScheduleRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
