// Code generated by mockery v2.53.6. DO NOT EDIT.

package schedule

import (
	context "context"

	model "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// mockRoomRepo is an autogenerated mock type for the roomRepo type
type mockRoomRepo struct {
	mock.Mock
}

// GetById provides a mock function with given fields: ctx, roomID
func (_m *mockRoomRepo) GetById(ctx context.Context, roomID string) (*model.Room, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Room, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Room); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockRoomRepo creates a new instance of mockRoomRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRoomRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRoomRepo {
	mock := &mockRoomRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
