// Code generated by mockery v2.53.6. DO NOT EDIT.

package user

import mock "github.com/stretchr/testify/mock"

// mockJwtManager is an autogenerated mock type for the jwtManager type
type mockJwtManager struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: userID, role
func (_m *mockJwtManager) GenerateToken(userID string, role string) (string, error) {
	ret := _m.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(userID, role)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockJwtManager creates a new instance of mockJwtManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockJwtManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockJwtManager {
	mock := &mockJwtManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
