// Code generated by mockery v2.53.6. DO NOT EDIT.

package room

import (
	context "context"

	model "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// mockRoomRepo is an autogenerated mock type for the roomRepo type
type mockRoomRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, room
func (_m *mockRoomRepo) Create(ctx context.Context, room *model.Room) (*model.Room, error) {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Room) (*model.Room, error)); ok {
		return rf(ctx, room)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Room) *model.Room); ok {
		r0 = rf(ctx, room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Room) error); ok {
		r1 = rf(ctx, room)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *mockRoomRepo) GetAll(ctx context.Context) ([]model.Room, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Room, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Room); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockRoomRepo creates a new instance of mockRoomRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRoomRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRoomRepo {
	mock := &mockRoomRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
