// Code generated by mockery v2.53.6. DO NOT EDIT.

package slot

import (
	context "context"
	time "time"

	model "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// mockSlotRepo is an autogenerated mock type for the slotRepo type
type mockSlotRepo struct {
	mock.Mock
}

// BulkCreate provides a mock function with given fields: ctx, slots
func (_m *mockSlotRepo) BulkCreate(ctx context.Context, slots []model.Slot) error {
	ret := _m.Called(ctx, slots)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Slot) error); ok {
		r0 = rf(ctx, slots)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountByRoomAndDate provides a mock function with given fields: ctx, roomID, date
func (_m *mockSlotRepo) CountByRoomAndDate(ctx context.Context, roomID string, date time.Time) (int, error) {
	ret := _m.Called(ctx, roomID, date)

	if len(ret) == 0 {
		panic("no return value specified for CountByRoomAndDate")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (int, error)); ok {
		return rf(ctx, roomID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) int); ok {
		r0 = rf(ctx, roomID, date)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, roomID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvailableByRoomAndDate provides a mock function with given fields: ctx, roomID, date
func (_m *mockSlotRepo) GetAvailableByRoomAndDate(ctx context.Context, roomID string, date time.Time) ([]model.Slot, error) {
	ret := _m.Called(ctx, roomID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableByRoomAndDate")
	}

	var r0 []model.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]model.Slot, error)); ok {
		return rf(ctx, roomID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []model.Slot); ok {
		r0 = rf(ctx, roomID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(ctx, roomID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockSlotRepo creates a new instance of mockSlotRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSlotRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSlotRepo {
	mock := &mockSlotRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
