// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/conference/conference.proto

package conference

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateConferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConferenceRequest) Reset() {
	*x = CreateConferenceRequest{}
	mi := &file_api_proto_conference_conference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConferenceRequest) ProtoMessage() {}

func (x *CreateConferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conference_conference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConferenceRequest.ProtoReflect.Descriptor instead.
func (*CreateConferenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conference_conference_proto_rawDescGZIP(), []int{0}
}

func (x *CreateConferenceRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type CreateConferenceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConferenceLink string                 `protobuf:"bytes,1,opt,name=conference_link,json=conferenceLink,proto3" json:"conference_link,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConferenceResponse) Reset() {
	*x = CreateConferenceResponse{}
	mi := &file_api_proto_conference_conference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConferenceResponse) ProtoMessage() {}

func (x *CreateConferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conference_conference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConferenceResponse.ProtoReflect.Descriptor instead.
func (*CreateConferenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_conference_conference_proto_rawDescGZIP(), []int{1}
}

func (x *CreateConferenceResponse) GetConferenceLink() string {
	if x != nil {
		return x.ConferenceLink
	}
	return ""
}

var File_api_proto_conference_conference_proto protoreflect.FileDescriptor

const file_api_proto_conference_conference_proto_rawDesc = "" +
	"\n" +
	"%api/proto/conference/conference.proto\x12\n" +
	"conference\"8\n" +
	"\x17CreateConferenceRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"C\n" +
	"\x18CreateConferenceResponse\x12'\n" +
	"\x0fconference_link\x18\x01 \x01(\tR\x0econferenceLink2r\n" +
	"\x11ConferenceService\x12]\n" +
	"\x10CreateConference\x12#.conference.CreateConferenceRequest\x1a$.conference.CreateConferenceResponseB\x10Z\x0epkg/conferenceb\x06proto3"

var (
	file_api_proto_conference_conference_proto_rawDescOnce sync.Once
	file_api_proto_conference_conference_proto_rawDescData []byte
)

func file_api_proto_conference_conference_proto_rawDescGZIP() []byte {
	file_api_proto_conference_conference_proto_rawDescOnce.Do(func() {
		file_api_proto_conference_conference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_conference_conference_proto_rawDesc), len(file_api_proto_conference_conference_proto_rawDesc)))
	})
	return file_api_proto_conference_conference_proto_rawDescData
}

var file_api_proto_conference_conference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_conference_conference_proto_goTypes = []any{
	(*CreateConferenceRequest)(nil),  // 0: conference.CreateConferenceRequest
	(*CreateConferenceResponse)(nil), // 1: conference.CreateConferenceResponse
}
var file_api_proto_conference_conference_proto_depIdxs = []int32{
	0, // 0: conference.ConferenceService.CreateConference:input_type -> conference.CreateConferenceRequest
	1, // 1: conference.ConferenceService.CreateConference:output_type -> conference.CreateConferenceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_conference_conference_proto_init() }
func file_api_proto_conference_conference_proto_init() {
	if File_api_proto_conference_conference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_conference_conference_proto_rawDesc), len(file_api_proto_conference_conference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_conference_conference_proto_goTypes,
		DependencyIndexes: file_api_proto_conference_conference_proto_depIdxs,
		MessageInfos:      file_api_proto_conference_conference_proto_msgTypes,
	}.Build()
	File_api_proto_conference_conference_proto = out.File
	file_api_proto_conference_conference_proto_goTypes = nil
	file_api_proto_conference_conference_proto_depIdxs = nil
}
