// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/conference/conference.proto

package conference

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConferenceService_CreateConference_FullMethodName = "/conference.ConferenceService/CreateConference"
)

// ConferenceServiceClient is the client API for ConferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConferenceServiceClient interface {
	CreateConference(ctx context.Context, in *CreateConferenceRequest, opts ...grpc.CallOption) (*CreateConferenceResponse, error)
}

type conferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConferenceServiceClient(cc grpc.ClientConnInterface) ConferenceServiceClient {
	return &conferenceServiceClient{cc}
}

func (c *conferenceServiceClient) CreateConference(ctx context.Context, in *CreateConferenceRequest, opts ...grpc.CallOption) (*CreateConferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConferenceResponse)
	err := c.cc.Invoke(ctx, ConferenceService_CreateConference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConferenceServiceServer is the server API for ConferenceService service.
// All implementations must embed UnimplementedConferenceServiceServer
// for forward compatibility.
type ConferenceServiceServer interface {
	CreateConference(context.Context, *CreateConferenceRequest) (*CreateConferenceResponse, error)
	mustEmbedUnimplementedConferenceServiceServer()
}

// UnimplementedConferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConferenceServiceServer struct{}

func (UnimplementedConferenceServiceServer) CreateConference(context.Context, *CreateConferenceRequest) (*CreateConferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConference not implemented")
}
func (UnimplementedConferenceServiceServer) mustEmbedUnimplementedConferenceServiceServer() {}
func (UnimplementedConferenceServiceServer) testEmbeddedByValue()                           {}

// UnsafeConferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConferenceServiceServer will
// result in compilation errors.
type UnsafeConferenceServiceServer interface {
	mustEmbedUnimplementedConferenceServiceServer()
}

func RegisterConferenceServiceServer(s grpc.ServiceRegistrar, srv ConferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedConferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConferenceService_ServiceDesc, srv)
}

func _ConferenceService_CreateConference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceServiceServer).CreateConference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceService_CreateConference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceServiceServer).CreateConference(ctx, req.(*CreateConferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConferenceService_ServiceDesc is the grpc.ServiceDesc for ConferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conference.ConferenceService",
	HandlerType: (*ConferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConference",
			Handler:    _ConferenceService_CreateConference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/conference/conference.proto",
}
