// Code generated by mockery v2.53.6. DO NOT EDIT.

package booking

import (
	context "context"

	model "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// mockSlotRepo is an autogenerated mock type for the slotRepo type
type mockSlotRepo struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, slotID
func (_m *mockSlotRepo) GetByID(ctx context.Context, slotID string) (*model.Slot, error) {
	ret := _m.Called(ctx, slotID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Slot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Slot, error)); ok {
		return rf(ctx, slotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Slot); ok {
		r0 = rf(ctx, slotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Slot)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockSlotRepo creates a new instance of mockSlotRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSlotRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSlotRepo {
	mock := &mockSlotRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
