// Code generated by mockery v2.53.6. DO NOT EDIT.

package booking

import (
	context "context"

	model "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// mockBookingRepo is an autogenerated mock type for the bookingRepo type
type mockBookingRepo struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, bookingID
func (_m *mockBookingRepo) Cancel(ctx context.Context, bookingID string) (*model.Booking, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 *model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Booking, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Booking); ok {
		r0 = rf(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: ctx
func (_m *mockBookingRepo) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, booking
func (_m *mockBookingRepo) Create(ctx context.Context, booking *model.Booking) (*model.Booking, error) {
	ret := _m.Called(ctx, booking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Booking) (*model.Booking, error)); ok {
		return rf(ctx, booking)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Booking) *model.Booking); ok {
		r0 = rf(ctx, booking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Booking) error); ok {
		r1 = rf(ctx, booking)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, limit, offset
func (_m *mockBookingRepo) GetAll(ctx context.Context, limit int, offset int) ([]model.Booking, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.Booking, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.Booking); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByUserID provides a mock function with given fields: ctx, userID
func (_m *mockBookingRepo) GetAllByUserID(ctx context.Context, userID string) ([]model.Booking, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByUserID")
	}

	var r0 []model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Booking, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Booking); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, bookingID
func (_m *mockBookingRepo) GetByID(ctx context.Context, bookingID string) (*model.Booking, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Booking, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Booking); ok {
		r0 = rf(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySlotID provides a mock function with given fields: ctx, slotID
func (_m *mockBookingRepo) GetBySlotID(ctx context.Context, slotID string) (*model.Booking, error) {
	ret := _m.Called(ctx, slotID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlotID")
	}

	var r0 *model.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Booking, error)); ok {
		return rf(ctx, slotID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Booking); ok {
		r0 = rf(ctx, slotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slotID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockBookingRepo creates a new instance of mockBookingRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBookingRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBookingRepo {
	mock := &mockBookingRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
