// Code generated by mockery v2.53.6. DO NOT EDIT.

package booking

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockConferenceClient is an autogenerated mock type for the conferenceClient type
type mockConferenceClient struct {
	mock.Mock
}

// CreateConference provides a mock function with given fields: ctx, bookingID
func (_m *mockConferenceClient) CreateConference(ctx context.Context, bookingID string) (string, error) {
	ret := _m.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for CreateConference")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, bookingID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockConferenceClient creates a new instance of mockConferenceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConferenceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConferenceClient {
	mock := &mockConferenceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
