// Code generated by mockery v2.53.6. DO NOT EDIT.

package schedule

import (
	context "context"

	dto "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// mockScheduleService is an autogenerated mock type for the scheduleService type
type mockScheduleService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, roomID, req
func (_m *mockScheduleService) Create(ctx context.Context, roomID string, req dto.ScheduleCreateRequest) (*dto.ScheduleResponse, error) {
	ret := _m.Called(ctx, roomID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.ScheduleResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ScheduleCreateRequest) (*dto.ScheduleResponse, error)); ok {
		return rf(ctx, roomID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.ScheduleCreateRequest) *dto.ScheduleResponse); ok {
		r0 = rf(ctx, roomID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ScheduleResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.ScheduleCreateRequest) error); ok {
		r1 = rf(ctx, roomID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockScheduleService creates a new instance of mockScheduleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockScheduleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockScheduleService {
	mock := &mockScheduleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
