// Code generated by mockery v2.53.6. DO NOT EDIT.

package slot

import (
	context "context"

	dto "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// mockSlotService is an autogenerated mock type for the slotService type
type mockSlotService struct {
	mock.Mock
}

// ListAvailable provides a mock function with given fields: ctx, roomID, date
func (_m *mockSlotService) ListAvailable(ctx context.Context, roomID string, date string) (*dto.SlotListResponse, error) {
	ret := _m.Called(ctx, roomID, date)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailable")
	}

	var r0 *dto.SlotListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.SlotListResponse, error)); ok {
		return rf(ctx, roomID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.SlotListResponse); ok {
		r0 = rf(ctx, roomID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SlotListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, roomID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockSlotService creates a new instance of mockSlotService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSlotService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSlotService {
	mock := &mockSlotService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
