// Code generated by mockery v2.53.6. DO NOT EDIT.

package room

import (
	context "context"

	dto "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// mockRoomService is an autogenerated mock type for the roomService type
type mockRoomService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *mockRoomService) Create(ctx context.Context, req dto.RoomCreateRequest) (*dto.RoomResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.RoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RoomCreateRequest) (*dto.RoomResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RoomCreateRequest) *dto.RoomResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RoomCreateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *mockRoomService) List(ctx context.Context) (*dto.RoomListResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *dto.RoomListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*dto.RoomListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *dto.RoomListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.RoomListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockRoomService creates a new instance of mockRoomService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRoomService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRoomService {
	mock := &mockRoomService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
