// Code generated by mockery v2.53.6. DO NOT EDIT.

package auth

import (
	context "context"

	dto "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// mockAuthService is an autogenerated mock type for the authService type
type mockAuthService struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, req
func (_m *mockAuthService) Login(ctx context.Context, req dto.UserLoginRequest) (*dto.UserLoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.UserLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserLoginRequest) (*dto.UserLoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserLoginRequest) *dto.UserLoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserLoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, req
func (_m *mockAuthService) Register(ctx context.Context, req dto.UserRegisterRequest) (*dto.UserRegisterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *dto.UserRegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserRegisterRequest) (*dto.UserRegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UserRegisterRequest) *dto.UserRegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserRegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UserRegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockAuthService creates a new instance of mockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuthService {
	mock := &mockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
