// Code generated by mockery v2.53.6. DO NOT EDIT.

package booking

import (
	context "context"

	dto "github.com/avito-internships/test-backend-1-mrpixik/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// mockBookingService is an autogenerated mock type for the bookingService type
type mockBookingService struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, userID, bookingID
func (_m *mockBookingService) Cancel(ctx context.Context, userID string, bookingID string) (*dto.CancelBookingResponse, error) {
	ret := _m.Called(ctx, userID, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 *dto.CancelBookingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.CancelBookingResponse, error)); ok {
		return rf(ctx, userID, bookingID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.CancelBookingResponse); ok {
		r0 = rf(ctx, userID, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CancelBookingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, bookingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, userID, req
func (_m *mockBookingService) Create(ctx context.Context, userID string, req dto.CreateBookingRequest) (*dto.CreateBookingResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.CreateBookingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.CreateBookingRequest) (*dto.CreateBookingResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.CreateBookingRequest) *dto.CreateBookingResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CreateBookingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.CreateBookingRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, req
func (_m *mockBookingService) List(ctx context.Context, req dto.AllBookingsRequest) (*dto.BookingListResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *dto.BookingListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.AllBookingsRequest) (*dto.BookingListResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.AllBookingsRequest) *dto.BookingListResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BookingListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.AllBookingsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *mockBookingService) ListByUserID(ctx context.Context, userID string) (*dto.MyBookingsResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 *dto.MyBookingsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.MyBookingsResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.MyBookingsResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.MyBookingsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockBookingService creates a new instance of mockBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBookingService {
	mock := &mockBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
